print(" ------------------------------------------------")
print("|                                                |")
print("|    03GoodbyePerson                             |")
print("|    Name : Amudha Bharathi                      |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello")
name = input("What is your name ? ")
print("Goodbye",name)