print(" ------------------------------------------------")
print("|                                                |")
print("|    04GoodTeacher                               |")
print("|    Name : Amudha Bharathi                      |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
teacher = input("Teacher's name (try Amudha) ")
print(teacher, "is an ok teacher")